kind: NetworkPolicy
apiVersion: networking.k8s.iov1
metadata:
  name: api-allw-5000
spec:
  podSelector:
    matchLabels:
      app: apiserver
  ingress:
  - ports:
    - port: 5000

---

kind: NetworkPolicy
apiVersion: networking.k8s.iov1
metadata:
  name: redis-allow-services
spec:
  podSelector:
    matchLabels:
      app: bookstore
      role: db
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: bookstore
            role: api
      - podSelector:
          matchLabels:
            app: inventory
            role: web

---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web-deny-all
spec:
  podSelector:
    matchLabels:
      app: web
  ingress:

---
kind: NetworkPolicy
apiVersion: networking.k8s.iov1
metadata:
  name: api-allow
spec:
  podSelector:
    matchLabels:
      app: bookstore
      role: api
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: bookstore